sonar.projectKey=RkotT0NS_OCR-P4
sonar.projectVersion=1.0.2
sonar.organization=RkotT0NS

sonar.sources=laravel,figma/implementation
sonar.tests=laravel/tests
sonar.test.inclusions=**/*Test.php
sonar.typescript.tsconfigPaths=figma/implementation/tsconfig.json,laravel/tsconfig.json
sonar.javascript.lcov.reportPaths=./lcov.info
sonar.php.coverage.reportPaths=./unified-clover.xml
